#!/bin/sh
set -e
set -x

action="$1"
oldversion="$2"
uuid_file='/etc/hostuuid'
create_uuid=''

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

. /usr/share/debconf/confmodule


test_uuid_file() {
	hostuuid --quiet --nostdin
}

test_uuid() {
	echo -n $RET | hostuuid --quiet
}


if [ "$1" = "configure" ] || [ "$1" = "reconfigure" ]; then
	if test_uuid_file; then
		exit 0
	else
		# this is set to high as _if_ someone installs this package, the
		# question is vital
		db_input high hostuuid/enter_uuid || true
		db_go
		db_get hostuuid/enter_uuid
		# if $RET is empty, generate a UUID
		if [ -z "$RET" ]; then
			echo $RET
#			hostuuid --create --quiet --nostdin
			hostuuid --create --nostdin
		else
			if test_uuid; then
#				hostuuid --create --quiet --nostdin --input $RET
				hostuuid --create --nostdin --input $RET
				exit 0
			else
				db_fset hostuuid/faulty_uuid seen false
				db_input critical hostuuid/faulty_uuid || true
				db_go
			fi
		fi
	fi
fi

exit 0

#DEBHELPER#
